import type { Metadata } from "next";
import Link from "next/link";
import { getApprovedReviews } from "@/lib/public-site";
import { ReviewForm } from "../_components/public-form";

export const metadata: Metadata = { title: "Verified Reviews", description: "Read moderated feedback from real Nexvia users and submit your own verified product review.", alternates: { canonical: "/reviews" } };

export default async function ReviewsPage() {
  const reviews = await getApprovedReviews();
  return <main className="mx-auto w-full max-w-6xl px-5 py-16 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Verified feedback</p><h1 className="mt-4 font-display text-4xl uppercase text-white sm:text-6xl">Real reviews, never invented testimonials.</h1><p className="mt-5 text-lg leading-8 text-slate-400">Only feedback submitted by signed-in users and approved after moderation appears here.</p></div><section className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{reviews.length ? reviews.map((review) => <article key={review.id} className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><p className="text-amber-300" aria-label={`${review.rating} out of 5 stars`}>{"★".repeat(review.rating)}<span className="text-slate-700">{"★".repeat(5 - review.rating)}</span></p><blockquote className="mt-4 leading-7 text-slate-200">“{review.review}”</blockquote><p className="mt-5 font-semibold text-white">{review.reviewer_name}</p><p className="text-xs text-slate-500">{review.reviewer_role}</p></article>) : <div className="md:col-span-2 lg:col-span-3 rounded-3xl border border-dashed border-white/15 p-10 text-center"><h2 className="text-xl font-semibold text-white">No approved pilot reviews yet</h2><p className="mt-2 text-slate-400">This honest empty state will be replaced as verified users submit feedback.</p></div>}</section><section className="mt-16 grid gap-8 rounded-3xl border border-violet-300/20 bg-violet-400/[.05] p-6 sm:p-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold text-white">Share your Nexvia experience</h2><p className="mt-3 leading-7 text-slate-400">You must be signed in. Submissions are moderated to remove spam and protect personal information.</p><Link href="/login" className="mt-5 inline-flex text-sm font-semibold text-cyan-300 hover:text-cyan-200">Sign in before reviewing →</Link></div><ReviewForm /></section></main>;
}
